package com.xcoder.easyinsta.exceptions;

public enum Reasons {
    REQUIRE_2_FACTOR_AUTHENTICATION,
    LOGIN_ERROR_UNKNOWN,
    BIO_LENGTH_EXCEEDED,
    UNSUPPORTED_FILE_FORMAT,
    INVALID_CREDENTIALS,
    CHALLENGE_REQUIRED,
    CACHING_ERROR,
    PROXY_ERROR,
    NO_SUCH_ADMIN,
    INVALID_USERNAME,
    LOGIN_TOO_FREQUENTLY,
    API_RESPONSE_ERROR,
    NO_SUCH_MESSAGE

}
