package com.xcoder.easyinsta;

public enum Reasons {
    REQUIRE_2_FACTOR_AUTHENTICATION,
    LOGIN_ERROR_UNKNOWN,
    BIO_LENGTH_EXCEEDED,
    UNSUPPORTED_FILE_FORMAT,
    INVALID_CREDENTIALS,
    CHALLENGE_REQUIRED,
    SERIALIZATION_ERROR,
    PROXY_ERROR,
    DESERIALIZATION_ERROR,
    LOGIN_TOO_FREQUENTLY
}
